check q&a for groups

In [2]:

#part 1 cid can be skipped for north pole passports
day6input=open("input.txt")
input = day6input.readlines()
input = [x.strip() for x in input]

In [4]:
print(len(input))
input[:10]

2080

['mxuwh', 'hwuxm', 'uhxmw', 'hwumx', 'hwuxm', '', 'k', 'k', 'tl', 'k']

In [59]:
groups = [set()]
for line in input:
    if (line == ''):
        groups.append(set())
    else:
        groups[-1].update(a for a in line)

In [60]:
print(len(groups))
groups[:3]

458

[{'h', 'm', 'u', 'w', 'x'},
 {'k', 'l', 't'},
 {'a',
  'b',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'k',
  'l',
  'n',
  'o',
  'q',
  'r',
  's',
  'u',
  'v',
  'w',
  'y',
  'z'}]

In [61]:
[len(group) for group in groups[-5:]]

[21, 16, 22, 15, 25]

In [62]:
sum([len(group) for group in groups])

6416

Part 2: need sum of counts of ALL party members answering the same

In [87]:
groups_all = [{}]
flag = True
for line in input:
    if (line == ''):
        flag = True
        groups_all.append({})
    elif flag:
        flag = False
        groups_all[-1] = set(a for a in line)
    else:
        groups_all[-1].intersection_update(a for a in line)

In [88]:
groups_all[:10]

[{'h', 'm', 'u', 'w', 'x'},
 set(),
 {'a', 'f', 'v'},
 {'i', 'p', 'q', 'r'},
 {'a', 'b', 'c', 'e', 'f', 'g', 'h', 'i', 'k', 'q', 't', 'y'},
 {'a', 'b', 'e', 'm', 'n', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'},
 {'e'},
 {'h', 'j'},
 {'d', 'e', 'i'},
 {'b', 'e', 'f', 'i', 'l', 'm', 'n', 'o', 'p', 't', 'u', 'v', 'x'}]

In [89]:
sum([len(group) for group in groups_all if len(group)>=1])

3050

In [90]:
[len(group) for group in groups_all]

[5,
 0,
 3,
 4,
 12,
 15,
 1,
 2,
 3,
 13,
 4,
 9,
 2,
 7,
 8,
 3,
 5,
 0,
 0,
 0,
 10,
 5,
 13,
 5,
 6,
 6,
 5,
 5,
 8,
 16,
 14,
 13,
 18,
 11,
 15,
 0,
 3,
 1,
 13,
 0,
 3,
 2,
 2,
 1,
 6,
 16,
 22,
 5,
 11,
 0,
 1,
 1,
 4,
 8,
 11,
 4,
 8,
 7,
 9,
 14,
 14,
 26,
 1,
 4,
 9,
 19,
 12,
 19,
 1,
 12,
 4,
 19,
 0,
 2,
 4,
 5,
 20,
 2,
 7,
 1,
 12,
 13,
 5,
 6,
 4,
 7,
 0,
 11,
 2,
 0,
 0,
 13,
 8,
 3,
 17,
 7,
 1,
 18,
 3,
 6,
 19,
 5,
 13,
 18,
 4,
 10,
 1,
 0,
 4,
 1,
 4,
 16,
 15,
 0,
 1,
 4,
 0,
 1,
 5,
 14,
 5,
 19,
 0,
 1,
 2,
 14,
 5,
 12,
 13,
 7,
 14,
 4,
 18,
 5,
 6,
 22,
 2,
 2,
 3,
 5,
 4,
 19,
 3,
 15,
 0,
 13,
 8,
 5,
 14,
 18,
 7,
 13,
 6,
 5,
 6,
 2,
 3,
 8,
 5,
 3,
 4,
 4,
 15,
 0,
 3,
 13,
 22,
 5,
 8,
 2,
 7,
 7,
 3,
 4,
 11,
 12,
 22,
 0,
 13,
 16,
 5,
 0,
 4,
 8,
 4,
 3,
 15,
 0,
 11,
 0,
 1,
 4,
 6,
 2,
 7,
 0,
 6,
 5,
 15,
 0,
 3,
 1,
 4,
 1,
 6,
 17,
 1,
 11,
 5,
 6,
 7,
 0,
 7,
 2,
 1,
 6,
 13,
 1,
 10,
 14,
 18,
 12,
 9,
 0,
 7,
 3,
 3,
 7,
 3,
 3,
 3,
 8,
 1,
 1,
 18,
 2,
 6,
 5,
 0,
 13,
 10,
 20,
 2,
 0,
 2,
 10,
 5,
 7,
 8,
 0,
 4,
 2,
 2,
 10,
 7,
 1,
 0,
 1,
 1,
 6,
 5,
 1,
 10,
 2,
 4,
 11,
 1,
 1,
 0,
 9,
 15,
 5,
 0,
 5,
 10,
 1,
 8,
 7,
 1,
 8,
 4,
 1,
 2,
 1,
 3,
 2,
 2,
 4,
 4,
 0,
 1,
 0,
 1,
 0,
 22,
 3,
 3,
 5,
 7,
 16,
 1,
 18,
 0,
 17,
 8,
 0,
 12,
 7,
 15,
 8,
 3,
 4,
 6,
 11,
 9,
 6,
 5,
 1,
 10,
 4,
 3,
 3,
 0,
 5,
 9,
 3,
 8,
 16,
 11,
 9,
 6,
 2,
 1,
 0,
 13,
 0,
 18,
 4,
 3,
 8,
 8,
 1,
 17,
 1,
 3,
 0,
 1,
 5,
 7,
 12,
 3,
 4,
 3,
 1,
 3,
 6,
 12,
 2,
 23,
 10,
 5,
 3,
 6,
 0,
 2,
 10,
 9,
 0,
 9,
 26,
 9,
 4,
 0,
 1,
 9,
 21,
 6,
 10,
 9,
 1,
 3,
 9,
 1,
 1,
 3,
 11,
 0,
 0,
 0,
 25,
 21,
 0,
 11,
 18,
 1,
 23,
 18,
 7,
 23,
 10,
 17,
 17,
 11,
 2,
 2,
 12,
 6,
 1,
 3,
 0,
 5,
 4,
 0,
 3,
 0,
 3,
 1,
 21,
 14,
 9,
 0,
 2,
 7,
 6,
 2,
 11,
 2,
 0,
 15,
 9,
 4,
 9,
 5,
 1,
 11,
 12,
 17,
 3,
 3,
 0,
 10,
 0,
 0,
 1,
 3,
 10,
 6,
 3,
 3,
 11,
 9,
 11,
 18,
 6,
 6,
 16,
 11,
 8]

In [91]:
print(len(input))
input[:20]

2080

['mxuwh',
 'hwuxm',
 'uhxmw',
 'hwumx',
 'hwuxm',
 '',
 'k',
 'k',
 'tl',
 'k',
 '',
 'qebagdfvhr',
 'alvkif',
 'yufaovwi',
 'fivsa',
 'nwifazovu',
 '',
 'ilpecrqn',
 'aipqgrfh',
 'pbwizrqv']

In [72]:
test_input = ["abc",
"",
"a",
"b",
"c",
"",
"ab",
"ac",
"",
"a",
"a",
"a",
"a",
"",
"b"]

In [85]:
groups_all_test = [{}]
flag = True
for line in test_input:
    if (line == ''):
        flag = True
        groups_all_test.append({})
    elif flag:
        flag = False
        groups_all_test[-1] = set(a for a in line)
    else:
        print('3',line)
        groups_all_test[-1].intersection_update(a for a in line)

3 b
3 c
3 ac
3 a
3 a
3 a

In [86]:
groups_all_test

[{'a', 'b', 'c'}, set(), {'a'}, {'a'}, {'b'}]